# Generated by Django 3.0 on 2020-12-28 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cl_medication', '0002_auto_20201228_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_record', models.DateTimeField(verbose_name='Дата и время записи пациента')),
            ],
        ),
        migrations.CreateModel(
            name='RecordPacientDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default=0, max_length=20, verbose_name='Телефон')),
                ('surname', models.CharField(blank=True, max_length=20, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=20, verbose_name='Отчество')),
                ('dob', models.DateField(blank=True, default=0, max_length=10, verbose_name='Дата рождения')),
                ('curent_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectMedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cl_medication.DiagnosSelect', verbose_name='Диагноз')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cl_medication.MedicationServices', verbose_name='Лечение')),
            ],
        ),
    ]
