# Generated by Django 3.0 on 2020-12-23 18:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cl_medication', '0001_initial'),
        ('cl_recorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordpacientdate',
            name='curent_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordpacientdate',
            name='dob',
            field=models.DateField(blank=True, default=0, max_length=10, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='recordpacientdate',
            name='patronymic',
            field=models.CharField(blank=True, max_length=20, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='recordpacientdate',
            name='phone',
            field=models.CharField(default=0, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='recordpacientdate',
            name='surname',
            field=models.CharField(blank=True, max_length=20, verbose_name='Фамилия'),
        ),
        migrations.CreateModel(
            name='SelectMedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cl_medication.DiagnosSelect', verbose_name='Диагноз')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cl_medication.MedicationServices', verbose_name='Лечение')),
            ],
            options={
                'index_together': {('diagnos', 'medication')},
            },
        ),
    ]
