# Generated by Django 3.0 on 2020-12-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('term', models.FloatField(default=0.0, verbose_name='Срок кадирования')),
                ('time_work', models.TimeField(default=0.0, verbose_name='Время работы')),
                ('price', models.FloatField(default=0.0, verbose_name='Стоимость')),
                ('diagnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cl_medication.DiagnosSelect', verbose_name='Диагноз')),
            ],
        ),
    ]
