# Generated by Django 3.0 on 2020-12-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_medication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosselect',
            options={'verbose_name_plural': 'Диагноз'},
        ),
        migrations.AlterModelOptions(
            name='medicationservices',
            options={'verbose_name_plural': 'Лечение'},
        ),
    ]
