# Generated by Django 3.0 on 2020-12-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectADisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100, verbose_name='Диагноз')),
            ],
            options={
                'verbose_name_plural': 'Диагноз',
            },
        ),
        migrations.CreateModel(
            name='SelectTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.FloatField(default=0.0, verbose_name='Год')),
            ],
            options={
                'verbose_name_plural': 'Срок',
            },
        ),
        migrations.CreateModel(
            name='ServicesAndPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('price', models.FloatField(default=0.0, verbose_name='Стоимость услуги')),
                ('selectadisease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease', to='cl_services.SelectTerm')),
                ('selecterm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectterm', to='cl_services.SelectTerm')),
            ],
            options={
                'verbose_name_plural': 'Услуги и цены',
            },
        ),
    ]
