# Generated by Django 3.0 on 2020-12-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesandprice',
            name='selectadisease',
        ),
        migrations.RemoveField(
            model_name='servicesandprice',
            name='selecterm',
        ),
    ]
