# Generated by Django 3.0 on 2020-12-14 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_services', '0002_auto_20201214_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesandprice',
            name='term',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cl_services.SelectTerm'),
        ),
    ]
