# Generated by Django 3.0 on 2020-12-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_services', '0003_servicesandprice_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesandprice',
            name='disease',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='diagnos', to='cl_services.SelectADisease'),
        ),
        migrations.AlterField(
            model_name='servicesandprice',
            name='term',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='termcod', to='cl_services.SelectTerm'),
        ),
    ]
