# Generated by Django 3.0 on 2020-12-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_services', '0004_auto_20201214_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesandprice',
            name='time_work',
            field=models.FloatField(default=1.0, max_length=5, verbose_name='Время процедуры'),
        ),
    ]
