# Generated by Django 3.0 on 2020-12-22 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cl_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Понедельник', max_length=12, verbose_name='День')),
                ('number', models.IntegerField(default=0, verbose_name='Номер')),
            ],
            options={
                'verbose_name_plural': 'Дни недели',
            },
        ),
        migrations.CreateModel(
            name='WorkinDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_work', models.CharField(max_length=50, verbose_name='Рабочие часы')),
                ('time_doctor', models.CharField(max_length=50, verbose_name='Прием врача')),
                ('happy_days', models.CharField(blank=True, max_length=150, verbose_name='Выходные дни')),
                ('week_day', models.ManyToManyField(default='', to='cl_calendar.Week', verbose_name='Рабочие дни')),
            ],
            options={
                'verbose_name_plural': 'Рабочие дни',
            },
        ),
        migrations.CreateModel(
            name='RegistrationDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('dob', models.DateField(max_length=10, verbose_name='Дата рождения')),
                ('curent_date', models.DateTimeField(auto_now_add=True)),
                ('diagnos', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='selects', to='cl_services.SelectADisease', verbose_name='Диагноз')),
                ('service_diagnos', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cl_services.ServicesAndPrice')),
            ],
            options={
                'verbose_name_plural': 'Запись к врачу',
            },
        ),
    ]
