# Generated by Django 3.0 on 2020-12-14 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_services', '0002_auto_20201214_1809'),
        ('cl_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkinDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_work', models.CharField(max_length=50, verbose_name='Рабочие часы')),
                ('time_doctor', models.CharField(max_length=50, verbose_name='Прием врача')),
                ('week_day', models.CharField(max_length=100, verbose_name='Рабочие дни')),
                ('happy_days', models.CharField(blank=True, max_length=150, verbose_name='Время')),
            ],
            options={
                'verbose_name_plural': 'Рабочие дни',
            },
        ),
        migrations.CreateModel(
            name='SelectServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cl_services.SelectADisease')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cl_services.ServicesAndPrice')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cl_services.SelectTerm')),
            ],
        ),
        migrations.AddField(
            model_name='registrationdate',
            name='selectservices',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='selects', to='cl_calendar.SelectServices'),
        ),
    ]
