# Generated by Django 3.0 on 2020-12-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdate',
            old_name='diagnos',
            new_name='disease',
        ),
    ]
