# Generated by Django 3.0 on 2020-12-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_calendar', '0005_auto_20201214_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workindays',
            name='week_day',
            field=models.CharField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенте')], default=6, max_length=6, verbose_name='Рабочие дни'),
        ),
    ]
