# Generated by Django 3.0 on 2020-12-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_calendar', '0006_auto_20201216_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='workindays',
            name='week_day',
        ),
        migrations.AddField(
            model_name='workindays',
            name='week_day',
            field=models.ManyToManyField(blank=True, null=True, related_name='work_days', to='cl_calendar.Week'),
        ),
    ]
