# Generated by Django 3.0 on 2020-12-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_calendar', '0007_auto_20201216_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='days',
            field=models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенте')], default=6),
        ),
        migrations.AlterField(
            model_name='workindays',
            name='week_day',
            field=models.ManyToManyField(default='Понедельник', to='cl_calendar.Week', verbose_name='Рабочие дни'),
        ),
    ]
