# Generated by Django 3.0 on 2020-12-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_calendar', '0008_auto_20201216_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'verbose_name_plural': 'Дни недели'},
        ),
        migrations.RemoveField(
            model_name='week',
            name='days',
        ),
        migrations.AddField(
            model_name='week',
            name='name',
            field=models.CharField(default='Понедельник', max_length=10, verbose_name='День'),
        ),
        migrations.AddField(
            model_name='week',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер'),
        ),
    ]
